name: automerge

on:
  pull_request:
    types:
      - labeled
      - reopened
      - unlocked
      - unlabeled
      - synchronize
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
    steps:
      -
        name: Automerge
        uses: pascalgn/automerge-action@v0.8.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS:
          MERGE_METHOD: squash
          MERGE_COMMIT_MESSAGE: automatic
      -
        name: Dispatch event
        uses: actions/github-script@v1
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.repos.createDispatchEvent({
              ...context.repo,
              event_type: 'ncc'
            })
